### ISSUE TITLE
Authentication Issue with ORE Linux

### ISSUE THREAD

**Issue by sseyedzadeh** [SmdhMdep/virtualHub#2]
When I try to connect to a Linux workspace by following the instructions, I get an error message when I type in my username at the end
The PuTTY Fatal Error is:
> No supported authentication method available (server sent: publickey,gssapi-keyex,gssapi-with-mic)

**Comment by aymanizz** [comment]
Hi @sseyedzadeh, if you see this error, you will also see that on the ORE dashboard a message appears in place of the "Connect" button saying

> The time window to connect has expired. To reset it, click on the Use this SSH Key button again.

Click on the "Use this SSH Key" button on the dashboard then go back to the AppStream tab and reconnect, it should work then.

**Comment by davidmeredith** [comment]
hi, can we close this ticket now?
